#! /bin/bash
#======================================================================
#
# autostart -
#
# Created by liubang on 2022/11/19 16:59
# Last Modified: 2022/11/19 16:59
#
#======================================================================

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}


run dunst &
run nm-applet &
run fcitx5 -d
run picom --experimental-backends -b

feh --no-fehbg --bg-scale "$HOME/.config/bspwm/wallpaper.png"
bash $HOME/.config/bspwm/polybar/launch.sh
xsetroot -cursor_name left_ptr
