#! /bin/sh

$HOME/.config/bspwm/autostart.sh

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' ''
		let name++
	done
}

workspaces

bspc config border_width          1
bspc config window_gap            10
bspc config split_ratio           0.5
bspc config focused_border_color  "#a89984"
bspc config normal_border_color   "#282828"
bspc config active_border_color   "#282828"
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        false
bspc config focus_follows_pointer true
bspc config pointer_modifier      mod1

# bspc rule -a kitty desktop='^2'
bspc rule -a Google-chrome       desktop='^1' state=tiled follow=on
bspc rule -a kitty               desktop='^2' state=tiled follow=on
bspc rule -a Zathura             desktop='^3' state=tiled follow=on
bspc rule -a Emacs               desktop='^3' state=floating follow=on
# bspc rule -a jetbrains-idea      desktop='^3' state=floating follow=on
bspc rule -a jetbrains-clion     desktop='^3' state=floating follow=on
bspc rule -a jetbrains-goland    desktop='^3' state=floating follow=on
bspc rule -a netease-cloud-music desktop='^4' state=floating follow=on
bspc rule -a mpv                 desktop='^5' state=floating follow=on
bspc rule -a TelegramDesktop     desktop='^6' state=floating follow=on
bspc rule -a Vmware              desktop='^7' state=floating follow=on
bspc rule -a Vmware Player       desktop='^7' state=floating follow=on
bspc rule -a VirtualBox Manager  desktop='^7' state=floating follow=on
