#!/bin/bash

export SXHKD_SHELL=/usr/bin/bash
export GDK_SCALE=1
export GDK_DPI_SCALE=1

LOGS=$HOME/.cache/bspwm/logs
exec >$LOGS/bspwm.log 2>&1

xsetroot -cursor_name left_ptr

deamonize() {
  echo "[start] $*"
  if pgrep "$1" >/dev/null; then
    echo "[warn] $1 is already running..."
  else
    "$@" >"$LOGS/$(basename "$1").log" 2>&1 &
  fi
}

deamonize sxhkd
deamonize dunst
deamonize nm-applet
deamonize blueman-applet
deamonize fcitx5 -d
deamonize picom
deamonize "$HOME/.config/bspwm/polybar/launch.sh"
deamonize feh --no-fehbg --bg-scale "$HOME/.config/bspwm/wallpaper/wallhaven-m99x9y.png"

# bspc monitor -d 1 2 3 4 5 6 7 8
bspc monitor -d '' '' '' '' '' '' ''

# workspaces() {
#   name=1
#   for monitor in `bspc query -M`; do
#       bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' ''
#       let name++
#   done
# }
# workspaces

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.5
bspc config focused_border_color "#a89984"
bspc config normal_border_color "#282828"
bspc config active_border_color "#282828"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

# 这里只能设置XDG class_name，通常，可以使用 xdotool和xprop来查看一个窗口的WM_CLASS
# xdotool search --name 'Peek preview' 根据窗口title获取窗口id
# xdotool search --pid 123 根据进程id获取窗口id
# xprop -id $winid | grep WM_CLASS 通过窗口id获取WM_CLASS

bspc rule -a 'Google-chrome' desktop='^1' state=tiled follow=on
bspc rule -a 'kitty' desktop='^2' state=tiled follow=on
bspc rule -a 'Alacritty' desktop='^2' state=tiled follow=on
bspc rule -a 'Zathura' desktop='^3' state=tiled follow=on
bspc rule -a 'Deno' state=tiled follow=on
bspc rule -a 'Emacs' desktop='^3' state=floating follow=on
bspc rule -a 'jetbrains-clion' desktop='^3' state=floating follow=on
bspc rule -a 'jetbrains-goland' desktop='^3' state=floating follow=on
bspc rule -a 'netease-cloud-music' desktop='^4' state=floating follow=on
bspc rule -a 'mpv' desktop='^5' state=floating follow=on
bspc rule -a 'TelegramDesktop' desktop='^6' state=floating follow=on
bspc rule -a 'QQ' desktop='^6' state=floating follow=on
bspc rule -a 'Thunderbird' desktop='^6' state=floating follow=on
bspc rule -a 'Vmware' desktop='^7' state=floating follow=on
bspc rule -a 'Vmware Player' desktop='^7' state=floating follow=on
bspc rule -a 'VirtualBox' desktop='^7' state=floating follow=on
bspc rule -a 'VirtualBox Manager' desktop='^7' state=floating follow=on
